"""Add FileUpload table

Revision ID: 1cda7fcc707d
Revises: 1a31ce608336
Create Date: 2026-01-18 20:40:16.151332

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1cda7fcc707d'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fileupload',
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('experiment', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('population', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('sensor', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fileupload')
    # ### end Alembic commands ###
